api/server.js, controllers/user.js, data/migrations/20191014152248_notifications.js, middleware/user-middleware.js, models/notifications.js
Added notifications migrations and GET and POST endpoints.
=> Notifications foundation

models/notifications.js
Small changes to notification model returned to the front end to fix errors with rendering.
=> Notification model changes to fix errors

api/server.js, controllers/notification.js, controllers/user.js, middleware/notification-middleware.js, models/notifications.js
Adds a delete endpoint to /api/notifications/:id to delete notifications by their id.
=> Add delete notifications by id endpoint

controllers/post_like.js, controllers/reply_like.js, models/replies_likes.js
appending replyLikes arr to response object
=> appending replyLikes arr to response object

api/server.js, index.js, models/notifications.js, package-lock.json, package.json
SocketIO integration for notifications, setting up connections for real-time notifications of likes, replies, and liked replies.
=> Back-end SocketIO integration for notifications

controllers/user.js, knexfile.js, models/notifications.js
=> finished delete functionality

controllers/tests/user.spec.js
Add basic notification testing on the back-end to verify integrity of the endpoints.
=> Add basic notification testing

models/notifications.js
Fix notifications returning as null from the back-end when trying to find deleted references.
=> fix null notifications

controllers/group.js, controllers/notification.js, controllers/post.js, models/groups.js, models/posts.js
Returning deleted rows from groups & posts that are deleted ....
=> Returning deleted rows

controllers/group.js, data/migrations/20191024103427_invitees.js, data/seeds/012-invitations.js, models/group_invitees.js
=> Invitations

api/server.js, controllers/group.js, controllers/join_private_group_request.js, controllers/user.js, data/migrations/20191025160645__join_private_group_request.js, data/seeds/003-groups.js, data/seeds/012-join_private_group_request.js, models/private_group_request.js, package-lock.json
Adds routes, tables, models, and seeds needed for private group access functionality including requesting access and rendering options for admins to accept/decline.
=> New routes, tables, and models for private group access functionality

controllers/group.js, controllers/group_user.js, models/group_invitees.js
Adds tweaks to invite by username instead of email and validating invites.
=> Add invite handling

controllers/user.js, data/migrations/20190815113645_users.js
Update to the migrations so that usernames are made unique and not nullable.
=> Make usernames unique and not-nullable

controllers/group.js
Return username in request object so that front-end has access to that information.
=> Return username in request

data/seeds/002-users.js, models/groups.js
=> Fixed seeds to match shape.

data/migrations/20190815113645_users.js, data/seeds/002-users.js
added an image property to the seeded faker user template and reran the seeds so the existing seeded users now include an image.
=> fixed seeded user data to include an image

controllers/group_user.js, controllers/tests/auth.spec.js, controllers/tests/group.spec.js, controllers/tests/user.spec.js
Add basic tests for group invites and requests to access private groups.
=> Add tests for invites and requests

controllers/group.js, controllers/group_user.js, controllers/join_private_group_request.js, controllers/user.js, data/db-config.js, models/groups.js
removing console logs that will dirty up the console
=> removed unneed console logs

index.js, namespaceHelpers/index.js, namespaceHelpers/root.js
created namespace handler func to handle future namespaces and abstract socket logic
=> Namespaces

namespaceHelpers/root.js
=> Reply post socket.io setup.

controllers/group.js, controllers/group_user.js, controllers/join_private_group_request.js, controllers/notification.js, controllers/user.js, data/db-config.js, index.js, models/groups.js, models/notifications.js, namespaceHelpers/index.js, namespaceHelpers/root.js
All posts, likes and replies update in real time.
=> All posts, likes and replies update in real time.

controllers/feed.js
Remove all code from feed except for posts.
Add likes and replies to feed posts.
=> Newsfeed update

controllers/auth.js, controllers/post.js
=> Route for group with id

controllers/post.js
Send group name back in the post result.
=> Send group name in post
